{ lib, ... }:
let
  # Same source of truth as modules/shared/nix-settings.nix.
  caches = import ../shared/_cache-list.nix;

  confText =
    ''
      # Generated by nix run .#bootstrap-cache — do not edit by hand.
      # This file is a bootstrap aid only: it pre-seeds the Nix daemon with the
      # shared binary cache list before the first `nixos-rebuild switch` that
      # would otherwise activate it.  Once the system is switched, the daemon
      # reads the same values from /etc/nix/nix.conf (managed by NixOS) and
      # this file is redundant but harmless.
      extra-substituters = ${lib.concatStringsSep " " caches.substituters}
      extra-trusted-public-keys = ${lib.concatStringsSep " " caches.trustedPublicKeys}
    '';
in
{
  perSystem =
    { pkgs, ... }:
    let
      confFile = pkgs.writeText "dendritic-caches.conf" confText;

      bootstrapCacheApp = pkgs.writeShellApplication {
        name = "bootstrap-cache";
        runtimeInputs = [ pkgs.coreutils ];
        text = ''
          set -euo pipefail

          dest=/etc/nix/conf.d/dendritic-caches.conf

          if [ "$(id -u)" -ne 0 ]; then
            echo "bootstrap-cache: must be run as root (use sudo nix run .#bootstrap-cache)" >&2
            exit 1
          fi

          mkdir -p /etc/nix/conf.d
          install -m 644 "${confFile}" "$dest"
          echo "bootstrap-cache: installed $dest"

          if systemctl is-active --quiet nix-daemon 2>/dev/null; then
            systemctl restart nix-daemon
            echo "bootstrap-cache: restarted nix-daemon"
          else
            echo "bootstrap-cache: nix-daemon is not running via systemd; restart it manually if needed"
          fi
        '';
        meta.description = "Pre-seed /etc/nix/conf.d with the shared binary cache list before first rebuild";
      };
    in
    {
      packages.bootstrap-cache-conf = confFile;

      apps.bootstrap-cache = {
        type = "app";
        program = "${bootstrapCacheApp}/bin/bootstrap-cache";
        meta.description = "Install shared binary cache config into /etc/nix/conf.d before first nixos-rebuild switch";
      };
    };
}
