is_wsl := path_exists("/proc/sys/fs/binfmt_misc/WSLInterop")
is_nixos := path_exists("/run/current-system/nixos-version")

rebuild_command := if os() == "macos" {
  "nix run .#nh -- darwin switch"
} else if os() == "linux" {
  if is_wsl == "true" {
    error("WSL is not supported yet")
  } else if is_nixos == "true" {
    "nix run .#nh -- os switch"
  } else {
    "nix run .#nh -- home switch"
  }
} else {
  error("Unsupported OS: " + os())
}

default:
  @just --list --unsorted

rebuild target=".":
  {{rebuild_command}} {{target}}

update:
  nix flake update

nix_sudo := if os() == "macos" { "sudo -H nix" } else { "nix" }
gc_command := if os() == "macos" {
  "sudo -H nix-env --profile /nix/var/nix/profiles/system --delete-generations"
} else {
  "nix profile wipe-history"
}
gc_day0_value := if os() == "macos" { "old" } else { "" }

gc days="7":
  {{gc_command}} \
    {{ if days == "0" { gc_day0_value } else { if os() == "macos" {"+" + days} else {"--older-than " + days + "d"} } }}
  {{nix_sudo}} store gc
